ministryofjustice/request-personal-information

app/controllers/requests_controller.rb, app/models/request_form/base.rb, app/models/request_form/letter_of_consent.rb, app/models/request_form/requester_id.rb, app/models/request_form/subject_id.rb, app/views/requests/_letter_of_consent.html.erb, app/views/requests/_requester_id.html.erb, app/views/requests/_subject_id.html.erb, spec/models/request_form/letter_of_consent_check_spec.rb, spec/models/request_form/letter_of_consent_spec.rb, spec/models/request_form/requester_details_spec.rb, spec/models/request_form/requester_id_check_spec.rb, spec/models/request_form/requester_id_spec.rb, spec/models/request_form/solicitor_details_spec.rb, spec/models/request_form/subject_date_of_birth_spec.rb, spec/models/request_form/subject_id_check_spec.rb, spec/models/request_form/subject_id_spec.rb, spec/models/request_form/subject_name_spec.rb, spec/models/request_form/subject_relationship_spec.rb, spec/models/request_form/subject_spec.rb, spec/requests/requester_spec.rb, spec/requests/subject_spec.rb, spec/support/shared_examples.rb
When going back to a previous step, show attributes previously entered.
Also handles file validation better so previously uploaded files are not overwritten.
=> CDPT-1609 Display form data and improve upload validation

app/controllers/requests_controller.rb, app/views/requests/_subject_id.html.erb, config/locales/en.yml, spec/requests/requester_spec.rb, spec/requests/subject_spec.rb
Also adds translations for when the subject is uploading their own ID.
=> Move upload requester ID before Letter of Consent

app/controllers/requests_controller.rb, app/models/request_form/base.rb, app/models/request_form/letter_of_consent.rb, app/models/request_form/requester_id.rb, app/models/request_form/subject_id.rb, spec/support/shared_examples.rb
The file was being overwritten on the form object before validation. The `updateable_attributes` method will stop that happening.
=> Fix large file validation

app/controllers/requests_controller.rb
The `current_step` value is not set before the first question page is loaded so checking it fails. Using `history` will check if a valid session is in place.
=> Fix first use bug

config/initializers/sentry.rb, config/kubernetes/staging/config_map.yml
Environment is being set as production in the staging environment. This sets `SENTRY_CURRENT_ENV` to be used instead.
=> Set correct environment

config/locales/en.yml, spec/mailers/notify_mailer_spec.rb, spec/models/information_request_summary_spec.rb, spec/requests/prison_information_spec.rb
- Move question mark to before "(optional)" https://dsdmoj.atlassian.net/browse/CDPT-1783
- Remove "(optional)" on pages where the whole question is marked as optional on the page https://dsdmoj.atlassian.net/browse/CDPT-1784
=> Fix optional usage

config/kubernetes/staging/ingress.yml
[Modsec](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/modsecurity.html) will stop malicious traffic going to the service.
=> CDPT-1958 Enable modsec in non-prod namespaces

.gitignore, app/views/pages/homepage.html.erb
On the landing page the link for the personal information charter should be in sentence case.
Addition of .Rubymine .idea folder to gitignore list.
Jira ticket:
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/864?assignee=557058%3A2d2f4a33-f427-483f-9c36-338caee60eae&selectedIssue=CDPT-2010
=> CDPT-2010 Update personal information charter link

app/controllers/requests_controller.rb
The form was breaking when using the back button and resubmitting a form. 
Disallowing caching makes it work. "no-store" is the required value, but "no-cache" is also required for older browsers (< IE10)
=> Fix back button bug

Gemfile.lock
=> Add ruby as platform

app/validators/file_type_validator.rb
Fixes issue with uploading word documents.
Removes invalid mime types:
- image/jpg
- application/doc
- application/docx
Adds
- application/rtf (.rtf)
- application/msword (.doc)
- application/vnd.openxmlformats-officedocument.wordprocessingml.document (.docx)
=> CDPT-2291 Update list of mime types

app/models/request_form/subject_address.rb, app/models/request_form/subject_id.rb, app/validators/file_type_validator.rb, spec/factories/attachments.rb, spec/factories/information_requests.rb, spec/requests/subject_spec.rb
Removes the custom filetypes defined in the models, and always uses the default.
Also sets the mimetype for the file used in tests to a valid one.
=> Use default allowed filetypes

app/controllers/requests_controller.rb
The back link was breaking when previously filled in options were removed as the forms still appeared in the session history.
The requirement for the form is now checked to see if it is still needed.
=> CDPT-2293 Check form is still required when going back

app/controllers/requests_controller.rb, app/models/request_form/letter_of_consent_check.rb, app/views/requests/_requester_id_check.html.erb, spec/factories/information_requests.rb, spec/features/request_by_family_spec.rb, spec/models/request_form/letter_of_consent_check_spec.rb, spec/requests/requester_spec.rb
When the user is not the subject and not a legal representative, the letter of consent check should be done at the same time as the requester ID check.
=> CDPT-2212 Add letter of consent to upload check page

app/controllers/requests_controller.rb, app/models/request_form/base.rb, app/views/requests/_letter_of_consent_check.html.erb, app/views/requests/_requester_id_check.html.erb, app/views/requests/_subject_id_check.html.erb, app/views/requests/edit.html.erb, spec/features/request_for_self_spec.rb, spec/support/shared_session_examples.rb
When a user wants to change an upload, once they have finished on that page the next step will take them back to the check page.
A `return_to` param has been added that will cause the submission of the form and the back link to use the value in the return_to param.
=> Allow straight return to check page

app/controllers/requests_controller.rb, app/models/information_request_summary.rb, app/views/requests/show.html.erb, spec/features/check_answers_spec.rb, spec/features/request_for_self_spec.rb, spec/requests/contact_spec.rb, spec/requests/other_information_spec.rb, spec/requests/requester_spec.rb
When the user makes a change from the "change-answers" page, after submitting they should be taken back to "check-answers" instead of having to go through all steps.
This does not apply to pages that can lead to additional information being required. e.g. if they change who is requesting the information, or what type of information is required.
=> CDPT-2250 Return to Check Answers page

app/views/layouts/application.html.erb
Amend the GOV.UK logo link to the https://www.gov.uk/
=> CDPT-2433 RPI: Amend the gov.uk link on page to navigate to Welcome GOV.UK

app/views/layouts/application.html.erb
Remove help link ( which takes the user to the gov.uk page ) from footer.
=> CDPT-2431 RPI: Remove help link from footer

app/controllers/pages_controller.rb, app/views/layouts/application.html.erb, app/views/pages/accessibility.html.erb, config/locales/en.yml, config/routes.rb, spec/requests/pages_spec.rb
Add the accessibility statement.
We discussed adding a back link or opening in a new tab, but have decided for now to do nothing. This is because we don't believe there is a standard practice and the back link required more work due to edge case bugs.
=> CDPT-2465: Create accessibility statement

Dockerfile, app/assets/config/manifest.js, app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb, config/initializers/assets.rb
Refactors how assets are made available from govuk-frontend. 
Adds `node_modules` to assets path to load the CSS, and adds the specific path to the assets folder for images and fonts.
Also copies assets to the public folder so they will be compiled for production use.
=> Fix favicon and how assets are made available

app/controllers/requests_controller.rb, spec/features/request_by_family_spec.rb, spec/features/request_by_solicitor_spec.rb, spec/features/request_for_self_spec.rb, spec/support/flow_helpers.rb
An issue with how the attachments are saved was causing invalid files to create entries into Attachments. This meant that validation was skipped and the user could bypass the file upload after triggering validation, and seemingly upload an invalid file.
This issue could possibly do with a refactor so that the attachments are not saved before the form validation happens. However for now I think it is sensible to delete the file once form validation has been triggered. We should potentially ticket up a refactor for the backlog. 
These methods in InformationRequest are potentially a bit of an issue:
```
def letter_of_consent=(file)
file_object = Attachment.create!(file:, key: "letter_of_consent")
self.letter_of_consent_id = file_object.id
end
def requester_photo=(file)
file_object = …
```
=> CDPT-2571: Fix invalid file saving
