ministryofjustice/request-personal-information

.github/workflows/test.yml, .gitignore, app/jobs/application_job.rb, app/mailers/application_mailer.rb, app/models/application_record.rb, app/views/pages/homepage.html.erb, spec/rails_helper.rb, spec/requests/pages_spec.rb, spec/requests/ping_spec.rb, spec/services/deployment_spec.rb
Create homepage.
Also adds tests for existing /ping page
=> CDPT-1342 Start page

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/requests_controller.rb, app/controllers/test/sessions_controller.rb, app/models/information_request.rb, app/models/request_form/base.rb, app/models/request_form/subject.rb, app/models/request_form/subject_name.rb, app/views/pages/homepage.html.erb, app/views/requests/_subject.html.erb, app/views/requests/_subject_name.html.erb, app/views/requests/show.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20240430144737_create_information_request.rb, db/schema.rb, spec/models/information_request_spec.rb, spec/models/request_form/subject_name_spec.rb, spec/models/request_form/subject_spec.rb, spec/rails_helper.rb, spec/requests/subject_spec.rb
Sets up basic framework for multi-step forms and creates the first two form pages.
=> Add first question pages

app/controllers/requests_controller.rb, app/models/information_request.rb, app/models/request_form/subject_date_of_birth.rb, app/views/requests/_subject_date_of_birth.html.erb, config/locales/en.yml, config/routes.rb, spec/models/information_request_spec.rb, spec/models/request_form/subject_date_of_birth_spec.rb, spec/models/request_form/subject_name_spec.rb, spec/rails_helper.rb, spec/requests/subject_spec.rb, spec/support/shared_examples.rb
Note: Attributes on the model don't need to be saved to the DB yet, so I will wait to create a migration until it is necessary.
=> Add date of birth question

Gemfile, Gemfile.lock, app/controllers/requests_controller.rb, app/models/information_request.rb, app/models/request_form/base.rb, app/models/request_form/subject_date_of_birth.rb, app/models/request_form/subject_relationship.rb, app/views/requests/_subject_date_of_birth.html.erb, app/views/requests/_subject_relationship.html.erb, config/locales/en.yml, config/routes.rb, spec/models/request_form/subject_date_of_birth_spec.rb, spec/models/request_form/subject_name_spec.rb, spec/models/request_form/subject_relationship_spec.rb, spec/models/request_form/subject_spec.rb, spec/requests/subject_spec.rb
Also fixes the data_of_birth question on the previous page, to make the data submission work.
=> Subject relationship question page

app/views/layouts/application.html.erb, app/views/shared/_debug.html.erb
- Add debug data in development
- Add header title
- Add phase banner
=> Debug data and header changes

app/controllers/requests_controller.rb, app/models/information_request.rb, app/models/request_form/hmpps.rb, app/views/requests/_hmpps.html.erb, config/locales/en.yml, config/routes.rb, spec/models/request_form/hmpps_spec.rb, spec/requests/information_spec.rb, spec/requests/subject_spec.rb
Select if information is needed from Prison or Probation services.
=> CDPT-1498 HMPPS page

app/models/request_form/letter_of_consent.rb, app/models/request_form/requester_id.rb, app/models/request_form/subject_id.rb, spec/support/shared_examples.rb
File size was not being validated if a previous upload existed.
=> Always validate file size

app/controllers/requests_controller.rb, app/models/information_request.rb, app/models/request_form/contact_address.rb, app/models/request_form/contact_email.rb, app/models/request_form/upcoming.rb, app/views/requests/_contact_address.html.erb, app/views/requests/_contact_email.html.erb, app/views/requests/_prison_location.html.erb, app/views/requests/_upcoming.html.erb, config/locales/en.yml, config/routes.rb, spec/models/request_form/contact_address_spec.rb, spec/models/request_form/contact_email_spec.rb, spec/models/request_form/upcoming_spec.rb, spec/requests/contact_spec.rb, spec/requests/other_information_spec.rb
- Contact address page
- Contact email page
- Upcoming hearing page
=> Add contact details pages

app/models/information_request_summary.rb, app/models/request_form/prison_location.rb, app/models/request_form/prison_number.rb, app/views/requests/_prison_location.html.erb, config/locales/en.yml, spec/factories/information_requests.rb, spec/models/information_request_summary_spec.rb, spec/models/request_form/prison_location_spec.rb, spec/models/request_form/prison_number_spec.rb, spec/requests/prison_information_spec.rb
Updates existing pages to change wording and validation when the subject of the request is also the requester.
=> Update for yourself path

app/views/requests/_laa_dates.html.erb, app/views/requests/_opg_dates.html.erb, app/views/requests/_other_dates.html.erb, app/views/requests/_prison_dates.html.erb, app/views/requests/_probation_dates.html.erb, app/views/requests/show.html.erb, spec/requests/check_answers_spec.rb
- Add some full stops to the copy
- hard code back link for the check answers page
=> Minor fixes

app/controllers/requests_controller.rb, app/models/information_request.rb, app/models/information_request_summary.rb, app/models/request_form/requester_details.rb, app/models/request_form/requester_id.rb, app/models/request_form/requester_id_check.rb, app/models/request_form/solicitor_details.rb, app/views/requests/_letter_of_consent_check.html.erb, app/views/requests/_requester_id_check.html.erb, app/views/requests/_subject_id_check.html.erb, app/views/requests/show.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20240603133735_add_to_information_request.rb, db/schema.rb, spec/models/information_request_spec.rb, spec/requests/check_answers_spec.rb, spec/requests/submission_spec.rb
- Save request in database and add validation
- get attachment directly from model
- Add by_family_or_friend? method
=> Save request

Gemfile, Gemfile.lock, config/kubernetes/staging/deployment.yml
Also adds missing gem needed by DelayedJob
=> Fix deploy yaml

spec/features/request_by_family_spec.rb, spec/features/request_by_solicitor_spec.rb, spec/features/request_for_self_spec.rb
Feature tests for the three different scenarios:
- Request for self
- Request by family/friend
- Request by solicitor
=> Feature tests

Dockerfile, README.md
- Update Dockerfile
- Fix setup instruction
=> Repo tweaks

app/models/request_form/subject.rb, config/locales/en.yml, spec/features/request_for_self_spec.rb, spec/requests/subject_spec.rb, spec/services/information_request_payload_spec.rb
Jira ticket:
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/864?assignee=557058%3A2d2f4a33-f427-483f-9c36-338caee60eae&selectedIssue=CDPT-2011
=> CDPT-2011 Update H1 and radio button content on subject page

config/locales/en.yml, spec/features/request_by_solicitor_spec.rb, spec/models/information_request_summary_spec.rb
Jira ticket:
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1152?assignee=557058%3A2d2f4a33-f427-483f-9c36-338caee60eae&assignee=unassigned&selectedIssue=CDPT-2016
=> CDPT-2016 Update conditional reveal text for "Something else" option

app/views/requests/_subject_name.html.erb, config/locales/en.yml
- Small bold font for form labels.
- Updated to text.
=> CDPT-2020 Update label size and hint text on on /subject-name

app/views/requests/_contact_address.html.erb, app/views/requests/_contact_email.html.erb, app/views/requests/_moj.html.erb, app/views/requests/_prison_information.html.erb, app/views/requests/_prison_location.html.erb, app/views/requests/_prison_number.html.erb, app/views/requests/_probation_information.html.erb, app/views/requests/_requester_details.html.erb, app/views/requests/_requester_id.html.erb, app/views/requests/_solicitor_details.html.erb, app/views/requests/_subject_id.html.erb, app/views/requests/_upcoming.html.erb
Jira ticket:
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/864?assignee=557058%3A2d2f4a33-f427-483f-9c36-338caee60eae&selectedIssue=CDPT-2047
=> CDPT-2047 Change all form labels size to 'Small'

app/models/information_request.rb, app/views/pages/homepage.html.erb, app/views/requests/_moj.html.erb, spec/features/request_by_solicitor_spec.rb, spec/features/request_for_self_spec.rb, spec/helpers/mail_helper_spec.rb, spec/mailers/notify_mailer_spec.rb, spec/models/information_request_spec.rb, spec/models/information_request_summary_spec.rb
Change Probation and Prison service names to sentence case.
Jira ticket:
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/864?assignee=557058%3A2d2f4a33-f427-483f-9c36-338caee60eae&selectedIssue=CDPT-2042
=> CDPT-2042 Update checkbox labels

Gemfile.lock
This is required for CI build to work.
=> Add ruby as platform

config/locales/en.yml, spec/requests/subject_spec.rb, spec/support/shared_validation.rb
=> Add space between number and unit

app/controllers/requests_controller.rb, app/models/request_form/letter_of_consent_check.rb, app/models/request_form/requester_id_check.rb, app/models/request_form/subject_id_check.rb, app/views/requests/_letter_of_consent_check.html.erb, app/views/requests/_requester_id_check.html.erb, app/views/requests/_subject_id_check.html.erb, config/locales/en.yml, spec/features/request_by_family_spec.rb, spec/features/request_by_solicitor_spec.rb, spec/features/request_for_self_spec.rb, spec/models/request_form/letter_of_consent_check_spec.rb, spec/models/request_form/requester_id_check_spec.rb, spec/models/request_form/subject_id_check_spec.rb, spec/requests/requester_spec.rb, spec/requests/subject_spec.rb
Remove the yes/no radio box as there are now links back to each upload.
=> Remove uploads confirmation 

config/kubernetes/production/deployment.yml, config/kubernetes/production/migrations.yml
=> Fix ECR URL

.github/workflows/deploy.yml, Dockerfile
PRs created by Dependabot don't have the correct permissions to authenticate to Cloud Platform
=> Don't build for dependabot

app/views/pages/homepage.html.erb, app/views/requests/complete.html.erb, app/views/requests/show.html.erb
Headings have jumped from H1 to H3
Replace the H3 with H2
=> CDPT-2439 RPI Update heading level

app/models/information_request.rb, app/views/requests/_prison_information.html.erb, spec/features/check_answers_spec.rb, spec/features/request_for_self_spec.rb, spec/mailers/notify_mailer_spec.rb, spec/models/information_request_spec.rb, spec/models/information_request_summary_spec.rb, spec/services/information_request_payload_spec.rb
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1152?selectedIssue=CDPT-2455
=> Change "NOMIS Records" to "NOMIS records"

app/controllers/pages_controller.rb, app/views/layouts/application.html.erb, app/views/pages/privacy.html.erb, config/locales/en.yml, config/routes.rb, spec/requests/pages_spec.rb
Basing off the accessibility statement for now as there is a little overlap. 
Add the privacy notice.
=> CDPT-2471: Add privacy notice

app/controllers/pages_controller.rb, app/views/layouts/_cookie_banner.html.erb, app/views/layouts/_cookie_banner_confirmation.html.erb, app/views/layouts/application.html.erb, app/views/pages/cookie_consent.html.erb, app/views/pages/privacy.html.erb, config/routes.rb, spec/features/cookie_banner_spec.rb, spec/features/cookies_page_spec.rb, spec/features/cookies_spec.rb
Contains details about cookies used on the service and a form allowing the user to change whether they consent to analytics cookies.
=> CDPT-2447 Add cookies page

config/kubernetes/production/ingress.yml
Fixes use of production domain
=> Use correct service name
